// Copyright 2021 Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

// This is an autogenerated file.
// Changes made to this file will be overwritten during the build process.

// Package version contains CLI version constant and utilities.

package version

const Version = "3.3.217.0"
